name: Auto-Clean

on:
  #自动清理：每天早上5点
  schedule:
    - cron: 0 21 * * *
  #手动清理
  workflow_dispatch:

permissions: write-all

jobs:
  auto_clean:
    runs-on: ubuntu-latest
    steps:
      - name: Delete old Releases and Workflows
        env:
          GH_TOKEN: ${{ github.token }}
          GH_REPO: ${{ github.repository }}
        run: |
          for run in $(gh run list --json databaseId -q '.[].databaseId'); do
            gh run delete "$run" && echo "删除运行记录 $run" || echo "运行记录 $run 无权限跳过"
          done
          for tag in $(gh release list -L 1000 --json tagName -q '.[].tagName'); do
            gh release delete "$tag" -y && echo "Release $tag 删除成功" || echo "Release $tag 删除失败"
          done
          for key in $(gh cache list -L 1000 --json key -q '.[].kay'); do
            gh cache delete "$key" -y && echo "cache $key 删除成功" || echo "cache $key 删除失败"
          done
